SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD UGB
JOIN    # 동일 인물 판별
    USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE   # 조건 : 판매된
    UGB.STATUS = 'DONE'
GROUP BY
    UGB.WRITER_ID
HAVING
    SUM(UGB.PRICE) >= 700000
ORDER BY
    TOTAL_SALES;