-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR T
    ON H.CAR_ID = T.CAR_ID
WHERE MONTH(H.START_DATE) = 10 AND T.CAR_TYPE = '세단'
GROUP BY H.CAR_ID
ORDER BY CAR_ID DESC;